### ISSUE TITLE
Bot stopped bump notifications pings

### ISSUE THREAD

**Issue by UntouchedOdin0** [TheDeveloperDen/DevDenBot#205]
The bot used to ping people, but as of last night around 10pm UK 13th December 2021 it stopped pinging people about the dishboard bump reminders.

**Comment by knightzmc** [comment]
This was due to it restarting after Emily's patch, so not a major issue, it happens every time the bot restarts. 

It would be nice to try and make it save the last bumped time so that it persists over restarts (potential PR?), But this isn't a big concern

**Comment by UntouchedOdin0** [comment]
Hey, thanks for the reply. I just wanted to report it incase it was something bigger.
