### ISSUE TITLE
Make bot easier to test locally

### ISSUE THREAD

**Issue by knightzmc** [TheDeveloperDen/DevDenBot#77]
way too coupled to the dev den server + vps rn, need to encourage PR testing by making it less dependant on being run on the server

**Comment by BlehKong** [comment]
I second this

**Comment by knightzmc** [comment]
I've made some progress towards this. Whilst many of the channel and role ids are still hardcoded, this can now run without Sentry and without a SQL database:

Set the `DDB_MOCK_DB` environment variable to anything (i.e not null), and the bot will use an in-memory H2 Database for storing data
Set `SENTRY_DSN` to `""` (or a valid DSN that you've setup) to run the bot without [sentry](https://sentry.io) - or if you have access to the Dev Den Sentry instance, you can get the actual DSN

Finally, set `DDB_TOKEN` to a valid discord bot token and the bot should run without issues
